### ISSUE TITLE
how to support 'require' and 'import' without MicroService

### ISSUE THREAD

**Issue by DmitryM9** [LiquidPlayer/LiquidCore#103]
I am building a project using functions
`npm install -g liquidcore-cli
liquidcore init example
cd example && npm install`

Then immediately perform the assembly
`npm run bundler -- --platform=android`

 I insert bundle into the Android raw folder
 In the android call code looks like this

`val jsContext = JSContext()
val str = resources.openRawResource(R.raw.liquid).bufferedReader().use { it.readText() }
jsContext.evaluateScript(str)`

 The application always closes with an error

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.optherium.vivexpay/com.optherium.vivexpay.activity.MainActivity}: ReferenceError: require is not defined
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: ReferenceError: require is not defined
        at org.liquidplayer.javascript.JSContext.evaluateScript(JSContext.java:272)
        at org.liquidplayer.javascript.JSContext.evaluateScript(JSContext.java:284)
        at com.optherium.vivexpay.activity.MainActivity.initFlow(MainActivity.kt:126)
        at com.optherium.vivexpay.activity.MainActivity.onCreate(MainActivity.kt:53)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ericwlange** [comment]
Are you certain you grabbed `liquid.bundle` and not `liquid.js`?

**Comment by DmitryM9** [comment]
yes, I am sure

**Comment by DmitryM9** [comment]
I will now create a test project with the bundle and send a link to it.

**Comment by ericwlange** [comment]
Oh sorry. Yes, this won't work. You must use a MicroService to enable
node.js. You can't just use the raw JavaScript engine if you want to use
the bundler. `require` is imolemented by node, not V8.

**Comment by DmitryM9** [comment]
Is it possible to somehow build the project in the bundle file without require? like browserify

**Comment by ericwlange** [comment]
I would have to look into it. But nothing is stopping you from using
browserify if it suits your needs. There is nothing in liquidcore bundle
that is magic. It is however optimized for nodejs and react native.

**Comment by DmitryM9** [comment]
Ok, thanks
