### ISSUE TITLE
SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by DhivinX** [LiquidPlayer/LiquidCore#147]
Hello,

when i'm generating the project by

` liquidcore init HelloWorld
cd HelloWorld && npm install`

**i see a lot of warnings:**

`npm WARN react-native@0.56.0 requires a peer of react@16.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-object-rest-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-optional-chaining@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-flow-strip-types@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-class-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-modules-commonjs@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-class-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-object-rest-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-optional-chaining@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-flow@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-async-to-generator@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/register@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-class-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-object-rest-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-proposal-optional-chaining@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-block-scoping@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-arrow-functions@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-computed-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-destructuring@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-classes@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-exponentiation-operator@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourse
lf.
npm WARN @babel/plugin-transform-flow-strip-types@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-for-of@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-literals@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-function-name@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-modules-commonjs@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-object-assign@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-parameters@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-display-name@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-jsx@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-jsx-source@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-regenerator@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-shorthand-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-template-literals@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-sticky-regex@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-unicode-regex@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-class-properties@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-object-rest-spread@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-optional-chaining@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-flow@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-syntax-jsx@7.0.0-beta.47 requires a peer of @babel/core@7.0.0-beta.47 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1151 packages from 471 contributors and audited 31719 packages in 54.839s
found 14 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
`

**so, when im run dev server:**

`C:\Users\x270\AndroidStudioProjects\Venom\microservice>npm run server

> microservice@0.0.1 server C:\Users\x270\AndroidStudioProjects\Venom\microservice
> node node_modules/liquidcore-cli/lib/cli.js server

Scanning folders for symlinks in C:\Users\x270\AndroidStudioProjects\Venom\microservice\node_modules (37ms)
C:\Users\x270\AndroidStudioProjects\Venom\microservice\node_modules\react-native\node_modules\metro\src\blacklist.js:38
  return new RegExp(
         ^

SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unter
minated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\Users\x270\AndroidStudioProjects\Venom\microservice\node_modules\react-native\node_modules\metro\src\blacklist.js:38:10)
    at Object.getBlacklistRE (C:\Users\x270\AndroidStudioProjects\Venom\microservice\node_modules\react-native\local-cli\util\Config.js:61:10)
    at getPackagerServer (C:\Users\x270\AndroidStudioProjects\Venom\microservice\node_modules\react-native\local-cli\server\runServer.js:182:25)
    at runServer (C:\Users\x270\AndroidStudioProjects\Venom\microservice\node_modules\react-native\local-cli\server\runServer.js:82:26)
    at server (C:\Users\x270\AndroidStudioProjects\Venom\microservice\node_modules\liquidcore-cli\lib\server.js:64:5)
    at Object.<anonymous> (C:\Users\x270\AndroidStudioProjects\Venom\microservice\node_modules\liquidcore-cli\lib\cli.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! microservice@0.0.1 server: `node node_modules/liquidcore-cli/lib/cli.js server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the microservice@0.0.1 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\x270\AppData\Roaming\npm-cache\_logs\2020-01-07T09_52_16_736Z-debug.log
`

What's wrong ?

**Comment by DhivinX** [comment]
Ok, its my mistake. it was enough run with admin rights.
