### ISSUE TITLE
Support for var args in JavaScript functions

### ISSUE THREAD

**Issue by buddhirajapraksh** [LiquidPlayer/LiquidCore#46]
Many web apis support variable number of arguments. For example: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D.

LiquidCore doesn't support var args for such APIs (Unless I am mistaken)

**Comment by ericwlange** [comment]
```java
JSContext context = new JSContext();
JSFunction myVaArgsCallback = new JSFunction(context, "va_concat") {
    JSValue va_concat(JSValue... args) {
        String concat = "";
        for (JSValue arg : args) {
            concat += arg.toString();
        }
        return new JSValue(context, concat);
    }
}
property(context, "va_concat", myVaArgsCallback);
```

```javascript
console.log(va_concat("1", 2, {3}, [4,5,6]);
```

_should_ work as you expect.  This code is untested, but please try it.

`JSValue` is the most generic value possible.  I allow other Java types for convenience, but if you need full flexibility, this should serve your needs.

**Comment by buddhirajapraksh** [comment]
Thanks for the sample @ericwlange, I will try it right away

**Comment by buddhirajapraksh** [comment]
I tried the sample (with few modifications) and got following exception:

```
Started running tests

Error: JSObject not an array
at org.liquidplayer.javascript.JSContext.evaluateScript(JSContext.java:252)
at org.liquidplayer.javascript.JSContext.evaluateScript(JSContext.java:265)
at org.liquidplayer.javascript.JSFunctionTest.varArgFunctionsTest(JSFunctionTest.java:602)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)

Tests ran to completion.
```

**Comment by buddhirajapraksh** [comment]
With attached patch, the test passed
[varargs.patch.log](https://github.com/LiquidPlayer/LiquidCore/files/1688968/varargs.patch.log)

**Comment by ericwlange** [comment]
This patch works great!  Checked into the project.  Thanks!

**Comment by ericwlange** [comment]
Now featured in 0.4.5.  Thanks for the contribution @buddhirajapraksh !

**Comment by buddhirajapraksh** [comment]
awesome! thanks for incorporating it @ericwlange
