### ISSUE TITLE
Unable to make an http request using request library at the server.

### ISSUE THREAD

**Issue by alphaguy4** [LiquidPlayer/LiquidCore#60]
Hi ,
I am trying to make an http request using request library as shown below : 
<pre>
LiquidCore.on( 'get_data', function() {
    //const request = require('request')
    request('https://opentdb.com/api.php?amount=10', function (error, response, body) {
      if (!error && response.statusCode == 200) {
        var importedJSON = JSON.parse(body)
        LiquidCore.emit('post',importedJSON)
      }
    })
    process.exit(0)
})
</pre>
Here is the error i am getting
<pre>
09-04 15:22:22.914 18866-19774/com.example.kartikay.liquidcoretestapp W/System.err: java.net.SocketTimeoutException: timeout
09-04 15:22:22.915 18866-19774/com.example.kartikay.liquidcoretestapp W/System.err:     at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
        at org.liquidplayer.service.MicroService.fetchService(MicroService.java:700)
        at org.liquidplayer.service.MicroService.onProcessStart(MicroService.java:741)
        at org.liquidplayer.node.Process.eventOnStart(Process.java:231)
        at org.liquidplayer.node.Process.access$800(Process.java:50)
        at org.liquidplayer.node.Process$2.__nodedroid_onLoad(Process.java:364)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.liquidplayer.javascript.JSFunction.function(JSFunction.java:546)
        at org.liquidplayer.javascript.JSFunction.functionCallback(JSFunction.java:496)
09-04 15:22:22.916 18866-19774/com.example.kartikay.liquidcoretestapp W/System.err: Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    	... 18 more
</pre>

What is the problem ?

**Comment by ericwlange** [comment]
Hi.  This is failing in attempt to fetch your micro service.  It hasn't even loaded your javascript yet.  What does your `MicroService` constructor look like?  Are you sure you have a server set up correctly?

**Comment by alphaguy4** [comment]
@ericwlange server is setup correctly (as given in the readme tutorial) as i tried testing it for sending json var like below:
<pre>
LiquidCore.on( 'get_data', function() {
    var jsonObj = {
    "available_topics" : [
        {
          "topic" : "Mathematics",
          "Description" : "NA"
        },
        {
          "topic" : "Science",
          "Description" : "NA"
        },
        {
          "topic" : "Movies",
          "Description" : "NA"
        }
    ]}
    LiquidCore.emit('post',jsonObj)
    process.exit(0)
})
</pre>
It works !!

**Comment by alphaguy4** [comment]
@ericwlange alright i have corrected the server error.but now i am not getting any response to the host app.

**Comment by ericwlange** [comment]
@alphaguy4 It is difficult to debug this without seeing a complete example, but is it possible that `if (!error && response.statusCode == 200) {` is not true?  You might want to emit some event on error to see if the request is failing.  As it's written it won't emit anything unless the request succeeds.

**Comment by ericwlange** [comment]
You can also liberally add `console.log()`s.  They will show up in your logcat.

**Comment by ericwlange** [comment]
Oh wait!  The problem is that you are calling `process.exit(0)` without waiting for the async response from `request`.
