### ISSUE TITLE
Unable to bundle websocket?

### ISSUE THREAD

**Issue by Piasy** [LiquidPlayer/LiquidCore#72]
I'm trying to use LiquidCore to run JS code (including WS communication) on Android, I run these commands below:

```bash
npm install -g liquidcore-cli
liquidcore init helloworld
cd helloworld && npm install
npm install websocket
# add "const W3CWebSocket = require('websocket').w3cwebsocket;" into index.js
npm run bundler
```

It fails with this error:

```bash
(node:90709) UnhandledPromiseRejectionWarning: 
Error: Unable to resolve module `../build/Release/bufferutil` from 
`/Users/piasy/Downloads/MediaSoupAndroid/helloworld/node_modules/websocket/lib/BufferUtil.js`: 
Module `../build/Release/bufferutil` does not exist in the Haste module map
```

It seem because websocket has two `.node` file, `bufferutil.node` and `validation.node`.

How could I fix that? Is it possible to do WS communication in JS?

**Comment by Piasy** [comment]
Thanks for your reply, I tried your suggestion, it get bundled successfully, but when I run the Micro App, the JS code fail with this error:

```bash
W/System.err: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at org.liquidplayer.javascript.JSFunction.function(JSFunction.java:546)
W/System.err:     at org.liquidplayer.javascript.JSFunction.functionCallback(JSFunction.java:496)
W/System.err:     at org.liquidplayer.node.Process.runInThread(Native Method)
W/System.err:     at org.liquidplayer.node.Process.access$100(Process.java:50)
W/System.err:     at org.liquidplayer.node.Process$1.run(Process.java:135)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
W/System.err: Caused by: TypeError: Cannot read property 'WebSocket' of undefined
W/System.err:     at org.liquidplayer.javascript.JSContext.evaluateScript(JSContext.java:232)
W/System.err:     at org.liquidplayer.javascript.JSContext.evaluateScript(JSContext.java:244)
W/System.err:     at org.liquidplayer.service.MicroService.onProcessStart(MicroService.java:754)
W/System.err:     at org.liquidplayer.node.Process.eventOnStart(Process.java:239)
W/System.err:     at org.liquidplayer.node.Process.access$1000(Process.java:50)
W/System.err:     at org.liquidplayer.node.Process$3.__nodedroid_onLoad(Process.java:372)
W/System.err: 	... 7 more
W/System.err: Error: java.lang.reflect.InvocationTargetException
W/System.err:     at org.liquidplayer.javascript.JSFunction.function(JSFunction.java:556)
W/System.err:     at org.liquidplayer.javascript.JSFunction.functionCallback(JSFunction.java:496)
W/System.err:     at org.liquidplayer.node.Process.runInThread(Native Method)
W/System.err:     at org.liquidplayer.node.Process.access$100(Process.java:50)
W/System.err:     at org.liquidplayer.node.Process$1.run(Process.java:135)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by ericwlange** [comment]
My mistake, of course that won't work.  The browser implementation of websocket uses the browser `window.WebSocket` constructor which does not exist in node.  Let me see if I can figure out a workaround.

As it stands, LiquidCore supports base node with all of its built-ins.  Outside of those built-ins, it can only support pure-JS implementations of other modules.  The vast majority of node modules are pure JS, but of course, some are not.  I am in the process of adding support for native modules (all of my recent commits are on this subject), but it is a tricky area because it requires cross-compilation, etc.

But let me see if I can find a way to use websocket with pure JS workarounds.

**Comment by Piasy** [comment]
Thanks for your reply!

I tried your suggestion, it won't throw any error now, and using W3CWebSocket to connect to WS server works well, thanks!
