### ISSUE TITLE
HttpURLConnection etc. dont work in JSFunction [Question]

### ISSUE THREAD

**Issue by emdy** [LiquidPlayer/LiquidCore#92]
Even with async task + while I can get value from url but I cant set value to return. 
Error: java.lang.reflect.InvocationTargetException.

**Comment by ericwlange** [comment]
Please post more of the stack trace.  It will have a more specific javascript error in it somewhere.

**Comment by emdy** [comment]
Android policy wont allow me to execute http get without async task: java.lang.NullPointerException.

Otherways how to get http url data in real time with JSFunction (wait for response to return)?

**Comment by ericwlange** [comment]
In your `AndroidManifest.xml`:

```xml
    <application
        android:usesCleartextTraffic="true">
    </application>
```

If that doesn't solve the problem, can you please copy and paste the entire stack trace?  I need more info.  It is all there in the trace, but I would need to see all of it.

**Comment by emdy** [comment]
Can you suggest how to implement http request with JSFunction and wait for response? 
Cant solve android.os.NetworkOnMainThreadException error. 

```
03-31 19:24:20.762 23474-23474/com.markody.internetproj E/helper1: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
        at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
        at java.net.InetAddress.getAllByName(InetAddress.java:215)
        at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:370)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:110)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:746)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:295)
        at com.markody.internetproj.MainActivity.onCreate(MainActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:6550)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3077)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3233)
        at android.app.ActivityThread.access$1000(ActivityThread.java:197)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6873)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

```

**Comment by ericwlange** [comment]
It's really difficult to try to understand what you are doing.  The exception above suggests that you are trying to query the network on the main thread, which is forbidden.  Any reason why you did that?  I'm guessing you just followed the example, which has the following:

```java
// NOTE: This event is typically called inside of the micro service's thread, not
 // the main UI thread.  To update the UI, run this on the main thread.
new Handler(Looper.getMainLooper()).post(new Runnable() {
    @Override
    public void run() {
        try {
            textView.setText(payload.getString("message"));
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }
});
```

The NOTE comment above is only true for updating the UI.  Don't do that for anything else, like networking.  You can run your code directly.  It shouldn't be run on the main looper.

In any event, why wouldn't you just use node's http capabilities?  For example, see [this blog](https://flaviocopes.com/node-make-http-requests/).  You can do it straight from javascript.  Why make a native function to do that?

**Comment by emdy** [comment]
I want to use jsoup.org in JSFunction to get result from url. 
From now I only want to get http data from url with .js script (evaluateScript).

**Comment by ericwlange** [comment]
(Algorithm ripped from [here](https://www.mkyong.com/java/how-to-send-http-request-getpost-in-java/))

```java
JSFunction sendGet = new JSFunction(context, "sendGet") {
    // HTTP GET request
    public String sendGet(String url) {
        try {
            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            // optional default is GET
            con.setRequestMethod("GET");

            //add request header
            con.setRequestProperty("User-Agent", USER_AGENT);

            int responseCode = con.getResponseCode();

            BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            return response.toString();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
};
context.property("sendGet");
```

from JavaScript:

```javascript
let url = 'http://whateverurlyouwant.com'
let response = sendGet(url)
// response is either null (if error) or the response string
```

**Comment by emdy** [comment]
It works only with StrictMode.ThreadPolicy or I will get same error: android.os.NetworkOnMainThreadException.
There is other option without StrictMode.ThreadPolicy and async task?

**Comment by ericwlange** [comment]
Can you make it asynchronous?

```java
JSFunction sendGet = new JSFunction(context, "sendGet") {
    // HTTP GET request
    public String sendGet(final String url, final JSFunction callback) {
        new Thread() {
            public void run() {
                try {
                    URL obj = new URL(url);
                    HttpURLConnection con = (HttpURLConnection) obj.openConnection();

                    // optional default is GET
                    con.setRequestMethod("GET");

                    //add request header
                    con.setRequestProperty("User-Agent", USER_AGENT);

                    int responseCode = con.getResponseCode();

                    BufferedReader in = new BufferedReader(
                        new InputStreamReader(con.getInputStream()));
                    String inputLine;
                    StringBuffer response = new StringBuffer();

                    while ((inputLine = in.readLine()) != null) {
                        response.append(inputLine);
                    }
                    in.close();

                    callback.call(null, response.toString());
                } catch (Exception e) {
                    e.printStackTrace();
                    callback.call(null, null, e.toString());
                }
            }
        }
    }).start();
};
context.property("sendGet");
```

Javascript:

```javascript
let url = 'http://whateverurlyouwant.com'
let response = sendGet(url, (body,error) => {
    if (error) {
        // Do error handling
    } else {
        // Response is in 'body'
    }
})
```

This doesn't seem to be a problem with LiquidCore, so I don't know how much more help I can be than [stackoverflow](https://stackoverflow.com/questions/6343166/how-do-i-fix-android-os-networkonmainthreadexception).

**Comment by emdy** [comment]
Great, works. Thanks for support.
